### ISSUE TITLE
"nil pointer dereference" after successful startup

### ISSUE THREAD

**Issue by RevinB** [disgoorg/disgo#133]
After updating to Go 1.18 and to disgo v0.8.3, I began getting nil pointer dereferences upon startup, after the `ready` event was fired. They only happened when the `Guild` intent was declared in gateway intents. I thought it was only an issue with my current project, so I copied and pasted the "Ping-pong" example from the README (with a minor change at the bottom, where `ChannelServices()` was renamed to `Channels()`), and got the exact same error.

### Exact error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x808db4]

goroutine 68 [running]:
github.com/disgoorg/disgo/gateway/handlers.(*gatewayHandlerGuildCreate).HandleGatewayEvent(0x4000345cc0?, {0xb9a8b0?, 0x400001a0c0}, 0x3, {0x951a00?, 0x4000312c80})
 	/go/pkg/mod/github.com/disgoorg/disgo@v0.8.3/gateway/handlers/guild_create_handler.go:90 +0x614
github.com/disgoorg/disgo/bot.(*eventManagerImpl).HandleGatewayEvent(0x40004267d0, {0x40006d9610, 0xc}, 0xc?, {0xb8a820, 0x4000737260})
 	/go/pkg/mod/github.com/disgoorg/disgo@v0.8.3/bot/event_manager.go:81 +0x128
github.com/disgoorg/disgo/gateway/handlers.DefaultGatewayEventHandler.func1({0x40006d9610, 0xc}, 0x10670?, {0xb8a820, 0x4000737260})
 	/go/pkg/mod/github.com/disgoorg/disgo@v0.8.3/gateway/handlers/all_handlers.go:25 +0xa0
github.com/disgoorg/disgo/gateway.(*gatewayImpl).listen(0x40003457c0)
 	/go/pkg/mod/github.com/disgoorg/disgo@v0.8.3/gateway/gateway_impl.go:353 +0x750
created by github.com/disgoorg/disgo/gateway.(*gatewayImpl).Open
	/go/pkg/mod/github.com/disgoorg/disgo@v0.8.3/gateway/gateway_impl.go:109 +0x4f0
```

I *am* running on an M1 MacBook, but I tested the README example in an Alpine Docker container and got the same result.

**Comment by TopiSenpai** [comment]
fixed in https://github.com/disgoorg/disgo/releases/tag/v0.8.4
thanks for reporting!
